# Generated by Django 6.1.1 on 2026-09-27 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('cereal', 'Cereal'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('legume', 'Legume'), ('oilseed', 'Oilseed'), ('cash_crop', 'Cash Crop'), ('spice', 'Spice'), ('other', 'Other')], default='other', max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_unit', models.CharField(choices=[('acres', 'Acres'), ('hectares', 'Hectares'), ('bigha', 'Bigha'), ('sq_meters', 'Square Meters')], default='acres', max_length=20)),
                ('soil_type', models.CharField(choices=[('alluvial', 'Alluvial'), ('black', 'Black (Regur)'), ('red', 'Red'), ('laterite', 'Laterite'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('other', 'Other')], default='other', max_length=20)),
                ('irrigation_type', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood'), ('rain_fed', 'Rain Fed'), ('canal', 'Canal'), ('well', 'Well/Borewell'), ('other', 'Other')], default='rain_fed', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('growing', 'Growing'), ('ready', 'Ready for Harvest'), ('harvested', 'Harvested')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crops.crop')),
            ],
            options={
                'verbose_name': 'Plant Image',
                'verbose_name_plural': 'Plant Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
