# Generated by Django 6.1.1 on 2026-09-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(db_index=True, max_length=100)),
                ('market_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('per_kg', '₹/kg'), ('per_quintal', '₹/quintal'), ('per_tonne', '₹/tonne'), ('per_dozen', '₹/dozen')], default='per_quintal', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('is_sample_data', models.BooleanField(default=False, help_text='True indicates this is demo/sample data, not a live price.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-date', 'crop_name'],
            },
        ),
    ]
