# Generated by Django 6.1.1 on 2026-09-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(db_index=True, max_length=100)),
                ('disease_name', models.CharField(max_length=200)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('prevention', models.TextField()),
                ('treatment', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['crop_name', 'disease_name'],
            },
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pesticide_type', models.CharField(choices=[('insecticide', 'Insecticide'), ('fungicide', 'Fungicide'), ('herbicide', 'Herbicide'), ('bactericide', 'Bactericide'), ('nematicide', 'Nematicide'), ('organic', 'Organic / Biopesticide')], max_length=20)),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(help_text='Application dosage / concentration', max_length=200)),
                ('application_method', models.TextField()),
                ('safety_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticides', to='diseases.disease')),
            ],
            options={
                'verbose_name': 'Pesticide',
                'verbose_name_plural': 'Pesticides',
            },
        ),
    ]
