# Generated by Django 6.1.1 on 2026-09-27 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('alluvial', 'Alluvial'), ('black', 'Black (Regur)'), ('red', 'Red'), ('laterite', 'Laterite'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('peaty', 'Peaty'), ('other', 'Other')], max_length=20)),
                ('ph', models.DecimalField(decimal_places=2, help_text='Soil pH (0–14). Optimal range: 6.0–7.5', max_digits=4)),
                ('nitrogen', models.DecimalField(decimal_places=2, help_text='Available Nitrogen in kg/ha', max_digits=8)),
                ('phosphorus', models.DecimalField(decimal_places=2, help_text='Available Phosphorus in kg/ha', max_digits=8)),
                ('potassium', models.DecimalField(decimal_places=2, help_text='Available Potassium in kg/ha', max_digits=8)),
                ('moisture', models.DecimalField(decimal_places=2, help_text='Soil moisture percentage (0–100)', max_digits=5)),
                ('organic_matter', models.DecimalField(decimal_places=2, help_text='Organic matter percentage (0–100)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soil Data',
                'verbose_name_plural': 'Soil Data Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
