# Generated by Django 4.2.30 on 2026-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='is_sample_data',
            field=models.BooleanField(default=False, help_text='True indicates this is demo/sample data and not a production soil record.'),
        ),
    ]
